#[cfg(feature = "bandcamp")]
pub mod bandcamp;
pub mod error;
#[cfg(feature = "google_music")]
pub mod google_music;
#[cfg(feature = "soundcloud")]
pub mod soundcloud;
#[cfg(feature = "spotify")]
pub mod spotify;
#[cfg(feature = "youtube")]
pub mod youtube;
